name: Run tests and deploy

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  check-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check coverage
        uses: themichaelhall/check-code-coverage@v2
        with:
          report: ./coverage/clover.xml
          required-percentage: 90
  deploy:
    runs-on: ubuntu-latest
    needs: check-coverage
    environment:
      name: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Upload dist
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1