name: Run tests and deploy

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  check-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check coverage
        run: |
          if [ ! -f ./coverage/coverage-summary.json ]; then
          echo "No coverage report"
          exit 1
          fi
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct | sed 's/%//')
          echo "Coverage is ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 75%" | bc -l) )); then
          echo "Test coverage below threshold, deployment aborted"
          exit 1
          fi
  deploy:
    runs-on: ubuntu-latest
    needs: check-coverage
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Set up Pages
        uses: actions/configure-pages@v3
      - name: Upload dist
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v1